### ISSUE TITLE
Syskit plugin

### ISSUE THREAD

**Issue by 2maz** [rock-core/drivers-transformer#13]
The following statement does not seem to be valid (any more ?) for master and fails with a method missing for 'reachable?': (ruby/transformer/syskit/plugin.rb +164)

```
prod_task.reachable?(task, Roby::TaskStructure::Dependency)
```

Changing to the following seems to do the job:

```
prod_task.plan.task_relation_graph_for(Roby::TaskStructure::Dependency).reachable?(prod_task,task)
```

**Comment by doudou** [comment]
Sorry for that one .... the amount of branching currently done on syskit/roby makes following things pretty difficult. I've backported the relevant commit: #14
